### ISSUE TITLE
CSGO Update from July 27th broke the pattern scanner

### ISSUE THREAD

**Issue by buzzel** [gabsens/Pattern-scanner-for-OSX#2]
```
LocalPlayer: 0x5145338
EntityList: 0x13e0c1f48
Glow: 0x85
```

Running the scanner, I get this. The glow and entity offsets are both wrong. One returns a full address and the other is just completely wrong.

**Comment by gabsens** [comment]
I've taken notice. Until I fix the broken pattern, here are the latest offsets
glowInfoOffset = 0x5954c00
LocalPlayerBase = 0x5145338
playerBase = 0x50C1F48
